// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using School.Modeling.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace School.Modeling.Models
{
    public partial interface ISchoolDbContextProcedures
    {
        Task<int> AgregarDepartamentoAsync(string p_Name, decimal? p_Budget, DateTime? p_StartDate, int? p_Administrator, int? p_CreateUser, OutputParameter<string> p_result, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerDepartamentosResult>> ObtenerDepartamentosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerDepartamentosPorNombreResult>> ObtenerDepartamentosPorNombreAsync(string p_Name, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateDepartamentoAsync(int? p_DepartmentId, string p_Name, decimal? p_Budget, DateTime? p_StartDate, int? p_Administrator, int? p_ModifyUser, OutputParameter<string> p_result, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
